let allProperties = [
  {
    id: 1,
    price: "\u20b91,50,00,000",
    type: "Premium Apartment",
    location: "Vesu, Surat, Gujarat",
    details: "3 BHK \u00b7 2 Bath \u00b7 1,650 sqft",
    image: "images/offers/apartment.jpg",
    status: "sale",
    description: "Spacious and stylish apartment ideal for modern living.",
  },
  {
    id: 2,
    price: "\u20b94,25,00,000",
    type: "Luxury Bungalow",
    location: "Alkapuri, Vadodara, Gujarat",
    details: "4 BHK \u00b7 3 Bath \u00b7 2,900 sqft",
    image: "images/offers/bungalow.jpg",
    status: "sale",
    description: "An expansive bungalow offering privacy and premium finishes.",
  },
  {
    id: 3,
    price: "\u20b975000/month",
    type: "Megastore",
    location: "Navrangpura, Ahmedabad, Gujarat",
    details: "Second Floor \u00b7 550 sqft",
    image: "images/offers/megastore.jpg",
    status: "rent",
    description:
      "Perfect location for retail operations with high foot traffic.",
  },
  {
    id: 4,
    price: "\u20b985000/month",
    type: "Office Space",
    location: "Rajkot, Gujarat",
    details: "1 Cabin,1 Washroom,900 sqft",
    image: "images/offers/office.jpg",
    status: "rent",
    description: "Functional and elegant office layout ideal for businesses.",
  },
  {
    id: 5,
    price: "\u20b91,25,00,000",
    type: "Spacious Garage",
    location: "Gandhinagar, Gujarat",
    details: "Capacity for 3 Cars \u00b7 750 sqft",
    image: "images/offers/garage.png",
    status: "sale",
    description: "Large garage space with ample room for multiple vehicles.",
  },
  {
    id: 6,
    price: "\u20b91,35,000/month",
    type: "Villa",
    location: "Udaipur, Rajasthan",
    details: "3 BHK \u00b7 2 Bath \u00b7 1,100 sqft",
    image: "images/offers/villa.jpg",
    status: "rent",
    description:
      "Contemporary villa with sleek interior and a private pool for luxurious living.",
  },
  {
    id: 7,
    price: "\u20b935000/month",
    type: "Retail Shop",
    location: "Whitefield, Bengaluru, Karnataka",
    details: "Ground Floor \u00b7 598 sqft",
    image: "images/property_images/property7.jpg",
    status: "rent",
    description: "Shop located in bustling commercial complex.",
  },
  {
    id: 8,
    price: "\u20b92,20,000/month",
    type: "Land Plot",
    location: "Bistupur, Jamshedpur, Jharkhand",
    details: "3264 sqft \u00b7 Road Facing \u00b7 Clear Title",
    image: "images/property_images/property8.jpg",
    status: "rent",
    description: "Clear titled plot perfect for investment.",
  },
  {
    id: 9,
    price: "\u20b91,30,000/month",
    type: "Luxury Bungalow",
    location: "Karelibaug, Vadodara, Gujarat",
    details: "5 BHK \u00b7 4 Bath \u00b7 3652 sqft",
    image: "images/property_images/property9.jpg",
    status: "rent",
    description: "Lavish bungalow offering tranquility and privacy.",
  },
  {
    id: 10,
    price: "\u20b91,70,000/month",
    type: "Premium Apartment",
    location: "Vesu, Surat, Gujarat",
    details: "4 BHK \u00b7 2 Bath \u00b7 1640 sqft",
    image: "images/property_images/property10.jpg",
    status: "rent",
    description: "Beautifully maintained apartment with all amenities.",
  },
  {
    id: 11,
    price: "\u20b985000/month",
    type: "Premium Apartment",
    location: "Kalavad Road, Rajkot, Gujarat",
    details: "4 BHK \u00b7 2 Bath \u00b7 1052 sqft",
    image: "images/property_images/property11.jpg",
    status: "rent",
    description: "Well-ventilated flat located in a prime neighborhood.",
  },
  {
    id: 12,
    price: "\u20b91,90,000/month",
    type: "Spacious Garage",
    location: "Andheri West, Mumbai, Maharashtra",
    details: "Capacity for 3 Cars \u00b7 947 sqft",
    image: "images/property_images/property12.jpg",
    status: "rent",
    description: "Spacious garage ideal for residential or commercial use.",
  },
  {
    id: 13,
    price: "\u20b91,55,000/month",
    type: "Premium Apartment",
    location: "Race Course, Vadodara, Gujarat",
    details: "3 BHK \u00b7 2 Bath \u00b7 1751 sqft",
    image: "images/property_images/property13.jpg",
    status: "rent",
    description: "Spacious apartment featuring open-plan interiors.",
  },
  {
    id: 14,
    price: "\u20b95,58,00,000",
    type: "Villa",
    location: "MG Road, Indore, Madhya Pradesh",
    details: "4 BHK \u00b7 5 Bath \u00b7 2086 sqft",
    image: "images/property_images/property14.jpg",
    status: "sale",
    description: "Luxurious villa with private pool and garden.",
  },
  {
    id: 15,
    price: "\u20b91,70,000/month",
    type: "Villa",
    location: "Sector 21, Gurgaon, Haryana",
    details: "4 BHK \u00b7 3 Bath \u00b7 3397 sqft",
    image: "images/property_images/property15.jpg",
    status: "rent",
    description: "Villa in gated community with 24/7 security.",
  },
  {
    id: 16,
    price: "\u20b91,78,00,000",
    type: "Luxury Bungalow",
    location: "Connaught Place, Delhi",
    details: "5 BHK \u00b7 3 Bath \u00b7 2606 sqft",
    image: "images/property_images/property16.jpg",
    status: "sale",
    description: "Bungalow with landscaped garden and ample natural light.",
  },
  {
    id: 17,
    price: "\u20b91,95,00,000",
    type: "Villa",
    location: "Gariahat, Kolkata, West Bengal",
    details: "4 BHK \u00b7 4 Bath \u00b7 3372 sqft",
    image: "images/property_images/property17.jpg",
    status: "sale",
    description: "Peaceful villa with lush surroundings.",
  },
  {
    id: 18,
    price: "\u20b94,04,00,000",
    type: "Luxury Bungalow",
    location: "Hazratganj, Lucknow, Uttar Pradesh",
    details: "5 BHK \u00b7 3 Bath \u00b7 2717 sqft",
    image: "images/property_images/property18.jpg",
    status: "sale",
    description: "Bungalow with landscaped garden and ample natural light.",
  },
  {
    id: 19,
    price: "\u20b985000/month",
    type: "Retail Shop",
    location: "Gariahat, Kolkata, West Bengal",
    details: "Ground Floor \u00b7 541 sqft",
    image: "images/property_images/property19.jpg",
    status: "rent",
    description: "Perfect shop for boutique or local business.",
  },
  {
    id: 20,
    price: "\u20b975000/month",
    type: "Premium Apartment",
    location: "Vaishali Nagar, Jaipur, Rajasthan",
    details: "3 BHK \u00b7 3 Bath \u00b7 1565 sqft",
    image: "images/property_images/property20.jpg",
    status: "rent",
    description: "Elegant apartment designed for comfortable urban living.",
  },
  {
    id: 21,
    price: "\u20b94,90,00,000",
    type: "Spacious Garage",
    location: "Nehru Place, Delhi",
    details: "Capacity for 2 Cars \u00b7 735 sqft",
    image: "images/property_images/property21.jpg",
    status: "sale",
    description: "Durable garage structure with electric shutter.",
  },
  {
    id: 22,
    price: "\u20b92,45,000/month",
    type: "Premium Apartment",
    location: "Perambur, Chennai, Tamil Nadu",
    details: "2 BHK \u00b7 3 Bath \u00b7 1518 sqft",
    image: "images/property_images/property22.jpg",
    status: "rent",
    description: "Beautifully maintained apartment with all amenities.",
  },
  {
    id: 23,
    price: "\u20b92,76,00,000",
    type: "Office Space",
    location: "Alambagh, Lucknow, Uttar Pradesh",
    details: "2 Cabin \u00b7 2 Washroom \u00b7 805 sqft",
    image: "images/property_images/property23.jpg",
    status: "sale",
    description: "Strategically located office ideal for startups.",
  },
  {
    id: 24,
    price: "\u20b982,00,000",
    type: "Premium Apartment",
    location: "Rajendra Nagar, Patna, Bihar",
    details: "2 BHK \u00b7 2 Bath \u00b7 1545 sqft",
    image: "images/property_images/property24.jpg",
    status: "sale",
    description: "Modern apartment with stunning city views.",
  },
  {
    id: 25,
    price: "\u20b93,80,00,000",
    type: "Retail Shop",
    location: "Gandhi Chowk, Jodhpur, Rajasthan",
    details: "Ground Floor \u00b7 521 sqft",
    image: "images/property_images/property25.jpg",
    status: "sale",
    description: "Retail space with modern interiors and lighting.",
  },
  {
    id: 26,
    price: "\u20b92,20,000/month",
    type: "Spacious Garage",
    location: "Adajan, Surat, Gujarat",
    details: "Capacity for 2 Cars \u00b7 923 sqft",
    image: "images/property_images/property26.jpg",
    status: "rent",
    description: "Modern garage with easy driveway access.",
  },
  {
    id: 27,
    price: "\u20b92,52,00,000",
    type: "Premium Apartment",
    location: "Lalpur, Ranchi, Jharkhand",
    details: "3 BHK \u00b7 3 Bath \u00b7 1211 sqft",
    image: "images/property_images/property27.jpg",
    status: "sale",
    description: "Elegant apartment designed for comfortable urban living.",
  },
  {
    id: 28,
    price: "\u20b94,71,00,000",
    type: "Retail Shop",
    location: "Salt Lake, Kolkata, West Bengal",
    details: "Ground Floor \u00b7 674 sqft",
    image: "images/property_images/property28.jpg",
    status: "sale",
    description: "Well-positioned shop with display windows.",
  },
  {
    id: 29,
    price: "\u20b92,10,000/month",
    type: "Luxury Bungalow",
    location: "Banjara Hills, Hyderabad, Telangana",
    details: "3 BHK \u00b7 3 Bath \u00b7 3040 sqft",
    image: "images/property_images/property29.jpg",
    status: "rent",
    description: "Lavish bungalow offering tranquility and privacy.",
  },
  {
    id: 30,
    price: "\u20b91,70,000/month",
    type: "Villa",
    location: "Dwarka, Delhi",
    details: "5 BHK \u00b7 4 Bath \u00b7 2109 sqft",
    image: "images/property_images/property30.jpg",
    status: "rent",
    description: "Villa in gated community with 24/7 security.",
  }
]